[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.{js,jsx,ts,tsx}"]
  external_node_modules = ["ethers"]

[functions."*"]
  timeout = 60

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Add environment variable to increase function timeout
  AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

